#!/usr/bin/env bash
# make-apply-all.sh: builds the ONE file a cross-repo session hands to the operator.
#
# The standing rule is in HANDOVER.md, "Cross-repo delivery". In short: each repo the session changed
# gets one squashed commit and one patch (`git format-patch -1 HEAD --binary --stdout`); this script
# packs those patches into a single self-contained `apply-all-<stamp>-<slug>.sh` that checks every repo, applies each
# patch in its own repo with `git am`, and pushes each one. The operator runs one command.
#
#   bash scripts/make-apply-all.sh --slug SLUG NAME:BRANCH:PATCHFILE [NAME:BRANCH:PATCHFILE ...]
#
#   bash scripts/make-apply-all.sh --slug task-43-icon-api \
#        zealot:develop:zealot.patch Storeapp:main:storeapp.patch D-Store:master:dstore.patch
#   -> writes ./apply-all-20261007-0912-task-43-icon-api.sh and prints its name
#
# THE FILE NAME IS UNIQUE PER DELIVERY (operator directive, 2026-10-07): `apply-all-YYYYMMDD-HHMM-SLUG.sh`,
# the time in UTC, SLUG a short lowercase name of the work (letters, digits, hyphens). `--slug` builds the
# name; `--out PATH` may be used instead of `--slug` and must end in a name of that same shape. The plain
# name `apply-all.sh` is refused, so a new delivery can never overwrite or be confused with an earlier file
# in the operator's downloads folder. One file per delivery; never reuse a name.
#
# NAME is the repo's folder name (and the GitHub repo name); BRANCH is the branch that repo's handover
# says to push to (Zealot `develop`, Storeapp `main`, D-Store `master`). The order given is the order of
# applying and pushing: put the repo the others depend on first (Zealot first, per the older rule).
# Patches are embedded as base64, so a patch that adds a binary file (a screenshot, an icon) survives.
#
# The generated script, run as `bash apply-all-<stamp>-<slug>.sh` (add `--check` to stop after the checks):
#   1. checks ALL repos before changing any: the checkout exists, is on BRANCH, has no uncommitted changes,
#      equals origin/BRANCH after a fetch (so no earlier patch is half applied and origin has not moved),
#      and the patch passes `git apply --check`;
#   2. applies each patch with `git am`; if one fails, it aborts that `am` and resets the repos it already
#      applied in this run back to where they started (nothing has been pushed yet);
#   3. pushes each repo to origin/BRANCH, never forced. A push that fails leaves its commit local; the
#      script says which repos were pushed and which were not.
# Checkout locations default to $HOME/NAME; override with NAME_DIR in upper case, other characters
# turned into `_` (ZEALOT_DIR, STOREAPP_DIR, D_STORE_DIR).
set -euo pipefail

usage() {
  echo "usage: bash make-apply-all.sh (--slug SLUG | --out apply-all-YYYYMMDD-HHMM-SLUG.sh) NAME:BRANCH:PATCHFILE [...]" >&2
  exit 2
}

NAME_SHAPE='^apply-all-[0-9]{8}-[0-9]{4}-[a-z0-9]+(-[a-z0-9]+)*\.sh$'
[[ $# -ge 3 ]] || usage
case "$1" in
  --slug)
    [[ $2 =~ ^[a-z0-9]+(-[a-z0-9]+)*$ ]] || { echo "slug must be lowercase letters, digits and hyphens: $2" >&2; exit 2; }
    out="apply-all-$(date -u +%Y%m%d-%H%M)-$2.sh" ;;
  --out)
    out="$2"
    [[ "$(basename "$out")" =~ $NAME_SHAPE ]] || { echo "the file name must look like apply-all-YYYYMMDD-HHMM-slug.sh (not the bare apply-all.sh): $out" >&2; exit 2; } ;;
  *) usage ;;
esac
shift 2
[[ ! -e $out ]] || { echo "$out already exists; names are never reused" >&2; exit 2; }
command -v base64 >/dev/null || { echo "base64 is needed" >&2; exit 1; }

names=(); branches=(); patches=()
for spec in "$@"; do
  IFS=: read -r name branch patch <<<"$spec"
  [[ -n ${name:-} && -n ${branch:-} && -n ${patch:-} ]] || usage
  [[ $name =~ ^[A-Za-z0-9._-]+$ ]] || { echo "bad repo name: $name" >&2; exit 2; }
  [[ $branch =~ ^[A-Za-z0-9._/-]+$ ]] || { echo "bad branch: $branch" >&2; exit 2; }
  [[ -s $patch ]] || { echo "patch file missing or empty: $patch" >&2; exit 2; }
  head -c 5 "$patch" | grep -q '^From ' || { echo "$patch is not a git format-patch file" >&2; exit 2; }
  names+=("$name"); branches+=("$branch"); patches+=("$patch")
done

{
  echo '#!/usr/bin/env bash'
  echo "# $(basename "$out"): generated by D-Store scripts/make-apply-all.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
  echo "# Repos, in order: ${names[*]}. Run: bash $(basename "$out")   (add --check to only run the checks)"
  echo 'set -euo pipefail'
  printf 'NAMES=('; printf '%q ' "${names[@]}"; echo ')'
  printf 'BRANCHES=('; printf '%q ' "${branches[@]}"; echo ')'
  echo 'tmp="$(mktemp -d)"; trap '"'"'rm -rf "$tmp"'"'"' EXIT'
  echo 'decode_patches() {'
  for i in "${!names[@]}"; do
    echo "  base64 -d > \"\$tmp/${i}.patch\" <<'__B64_END_${i}__'"
    base64 < "${patches[$i]}"
    echo "__B64_END_${i}__"
  done
  echo '}'
  cat <<'RUNTIME'
decode_patches

CHECK_ONLY=0
[[ ${1:-} == "--check" ]] && CHECK_ONLY=1
fail() { echo "STOPPED: $*" >&2; exit 1; }
dir_for() {
  local var; var="$(printf '%s' "$1" | tr 'a-z.-' 'A-Z__')_DIR"
  printf '%s' "${!var:-$HOME/$1}"
}

echo "== Step 1: checking every repo (nothing is changed yet)"
starts=()
for i in "${!NAMES[@]}"; do
  name="${NAMES[$i]}"; branch="${BRANCHES[$i]}"; dir="$(dir_for "$name")"
  [[ -d $dir/.git ]] || fail "$name: no git checkout at $dir (set $(printf '%s' "$name" | tr 'a-z.-' 'A-Z__')_DIR)"
  cd "$dir"
  [[ "$(git rev-parse --abbrev-ref HEAD)" == "$branch" ]] || fail "$name: on '$(git rev-parse --abbrev-ref HEAD)', not '$branch'"
  [[ -z "$(git status --porcelain --untracked-files=no)" ]] || fail "$name: uncommitted changes in $dir"
  git fetch -q origin "$branch" || fail "$name: cannot reach origin"
  [[ "$(git rev-parse HEAD)" == "$(git rev-parse "origin/$branch")" ]] \
    || fail "$name: local $branch differs from origin/$branch (an earlier patch half applied, or origin moved). Do not force; report back."
  git apply --check "$tmp/$i.patch" || fail "$name: the patch does not apply to $(git rev-parse --short HEAD)"
  starts+=("$(git rev-parse HEAD)")
  echo "   ok  $name  $branch @ $(git rev-parse --short HEAD)"
done
[[ $CHECK_ONLY == 1 ]] && { echo "Checks passed. Nothing was applied (--check)."; exit 0; }

echo "== Step 2: applying with git am"
applied=()
rollback() {
  local j
  for j in "${applied[@]}"; do
    (cd "$(dir_for "${NAMES[$j]}")" && git reset -q --hard "${starts[$j]}") && echo "   rolled back ${NAMES[$j]}" >&2
  done
}
for i in "${!NAMES[@]}"; do
  name="${NAMES[$i]}"; cd "$(dir_for "$name")"
  if ! git am -q "$tmp/$i.patch"; then
    git am --abort >/dev/null 2>&1 || true
    rollback
    fail "$name: git am failed. Everything was put back as it was; nothing was pushed."
  fi
  applied+=("$i")
  echo "   applied  $name"
done

echo "== Step 3: pushing (never forced)"
pushed=()
for i in "${!NAMES[@]}"; do
  name="${NAMES[$i]}"; branch="${BRANCHES[$i]}"; cd "$(dir_for "$name")"
  if ! git push origin "$branch"; then
    echo "STOPPED: $name: push failed; its commit is local at $(pwd)." >&2
    echo "  pushed: ${pushed[*]:-none}" >&2
    echo "  not pushed: $name and every repo after it. Fix access, then run 'git push' in each of those folders." >&2
    exit 1
  fi
  pushed+=("$name")
  echo "   pushed   $name -> origin/$branch @ $(git rev-parse --short HEAD)"
done

echo
echo "Done. Heads now:"
for i in "${!NAMES[@]}"; do
  echo "   ${NAMES[$i]} ${BRANCHES[$i]} @ $(cd "$(dir_for "${NAMES[$i]}")" && git rev-parse --short HEAD)"
done
echo "Next: check the CI run each push started (the repo's own handover says which workflow is the one to read)."
RUNTIME
} > "$out"

chmod +x "$out"
bash -n "$out" || { echo "generated script has a syntax error" >&2; exit 1; }
echo "wrote $out (${#names[@]} repo(s): ${names[*]}); run it with: bash $out"
