<?php

namespace Melodycode\FossdroidBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReportFlagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportFlagRepository extends EntityRepository {

    /**
     * Finds reports by status, newest first — what the future admin
     * review queue (2.b.iii.zo) needs to list open reports. That
     * controller/UI doesn't exist yet; this only provides the query.
     */
    public function findByStatus($status) {
        $entityManager = $this->getEntityManager();

        $query = $entityManager->createQueryBuilder()
                ->select('r')
                ->from('MelodycodeFossdroidBundle:ReportFlag', 'r')
                ->where('r.status = :status')
                ->setParameter('status', $status)
                ->orderBy('r.created_at', 'DESC');

        return $query->getQuery()->getResult();
    }

}
