<?php

namespace Melodycode\FossdroidBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends EntityRepository {

    /**
     * Counts reviews from a given ip_hash for a given application since
     * a given time — what a rate-limit check needs ("has this source
     * already submitted N reviews for this app in the last X?"). The
     * limit itself (N, X) and the controller-level rejection belong to
     * a later leaf once the API layer exists; this only provides the
     * query.
     */
    public function countByIpHashSince($ipHash, $applicationId, \DateTime $since) {
        $entityManager = $this->getEntityManager();

        $query = $entityManager->createQueryBuilder()
                ->select('COUNT(r.id)')
                ->from('MelodycodeFossdroidBundle:Review', 'r')
                ->where('r.ip_hash = :ip_hash')
                ->andWhere('r.application = :application_id')
                ->andWhere('r.created_at >= :since')
                ->setParameter('ip_hash', $ipHash)
                ->setParameter('application_id', $applicationId)
                ->setParameter('since', $since);

        return $query->getQuery()->getSingleScalarResult();
    }

}
